// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rihbsvtikdwqqgfmvitx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpaGJzdnRpa2R3cXFnZm12aXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzMwMDQsImV4cCI6MjA2MDcwOTAwNH0.H9-W_Swzc8nRKcpVMP81m7K2flCsUAW1jcvWn2LSqUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);